=== lsuonline/lsuce-moodle/local/xml/schema/COURSES.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rows">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="ROW" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    
    <xs:complexType name="rowType">
        <xs:all>
            <!-- This element is not currently used, but there is
            every reason to think it may be useful in the future. -->
            <xs:element name="CAMPUS_CODE" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="DEPT_CODE" type="xs:string"/>
            <xs:element name="COURSE_NBR" type="courseNumberType"/>
            <xs:element name="SECTION_NBR" type="xs:string"/>
            <xs:element name="CLASS_TYPE" type="xs:string"/>
            <xs:element name="COURSE_TITLE" type="xs:string"/>
            <xs:element name="GRADE_SYSTEM_CODE" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="departmentType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="courseNumberType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fullnameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sectionNumberType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="classTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LAB" />
            <xs:enumeration value="LEC" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== lsuonline/lsuce-moodle/blocks/sgelection/enrollment/COURSES.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/COURSES.xsd">
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>002</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>003</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>004</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>005</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>006</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>007</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>008</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>009</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>010</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>011</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>Multimedia</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>012</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>INTRO to Panopto</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
</rows>

=== lsuonline/lsuce-moodle/local/xml/sample_enrollment/COURSES.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/COURSES.xsd">
    <ROW>

        <DEPT_CODE>TST2</DEPT_CODE>
        <COURSE_NBR>2010</COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <CLASS_TYPE>LAB</CLASS_TYPE>
        <COURSE_TITLE>INQ MATH &amp; SCI TEACH</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <CAMPUS_CODE>01</CAMPUS_CODE>
        <DEPT_CODE>Biology</DEPT_CODE>
        <COURSE_NBR>101c</COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>Intro to Organic Darwinism</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
</rows>

=== lsuonline/lsuce-moodle/blocks/sgelection/tests/behat/enrolments/COURSES.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/COURSES.xsd">
    <ROW>
        <DEPT_CODE>TEST</DEPT_CODE>
        <COURSE_NBR>1001</COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>Behat test course</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
    <ROW>
        <DEPT_CODE>TEST</DEPT_CODE>
        <COURSE_NBR>9000</COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <CLASS_TYPE>LEC</CLASS_TYPE>
        <COURSE_TITLE>Behat test seminar</COURSE_TITLE>
        <GRADE_SYSTEM_CODE>L</GRADE_SYSTEM_CODE>
    </ROW>
</rows>
