=== lsuonline/lsuce-moodle/local/xml/schema/INSTRUCTORS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rows">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="ROW" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="rowType">
        <xs:all>
            <xs:element name="IDNUMBER" type="xs:string"/>
            <xs:element name="PRIMARY_INSTRUCTOR" type="xs:string"/>
            <xs:element name="CLASS_DEPT_CODE" type="xs:string"/>
            <xs:element name="CLASS_COURSE_NBR" type="xs:string"/>
            <xs:element name="SECTION_NBR" type="xs:string"/>
            <xs:element name="INDIV_NAME" type="xs:string"/>
            <xs:element name="PRIMARY_ACCESS_ID" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== lsuonline/lsuce-moodle/blocks/sgelection/tests/behat/enrolments/INSTRUCTORS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/INSTRUCTORS.xsd">
    <ROW>
       <IDNUMBER>testinst001</IDNUMBER>
        <PRIMARY_INSTRUCTOR>Y</PRIMARY_INSTRUCTOR>
        <CLASS_DEPT_CODE>TEST</CLASS_DEPT_CODE>
        <CLASS_COURSE_NBR>1001</CLASS_COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <INDIV_NAME>instructor001, test</INDIV_NAME>
        <PRIMARY_ACCESS_ID>testinst001</PRIMARY_ACCESS_ID>
    </ROW>
    <ROW>
       <IDNUMBER>testinst001</IDNUMBER>
        <PRIMARY_INSTRUCTOR>Y</PRIMARY_INSTRUCTOR>
        <CLASS_DEPT_CODE>TEST</CLASS_DEPT_CODE>
        <CLASS_COURSE_NBR>9000</CLASS_COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <INDIV_NAME>instructor001, test</INDIV_NAME>
        <PRIMARY_ACCESS_ID>testinst001</PRIMARY_ACCESS_ID>
    </ROW>
</rows>

=== lsuonline/lsuce-moodle/local/xml/sample_enrollment/INSTRUCTORS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/INSTRUCTORS.xsd">
    <ROW>
        <IDNUMBER>123456789</IDNUMBER>
        <PRIMARY_INSTRUCTOR/>
        <CLASS_DEPT_CODE>TST2</CLASS_DEPT_CODE>
        <CLASS_COURSE_NBR>2010</CLASS_COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <INDIV_NAME>1, instructor</INDIV_NAME>
        <PRIMARY_ACCESS_ID>inst1</PRIMARY_ACCESS_ID>
    </ROW>
    <ROW>
        <IDNUMBER>234555</IDNUMBER>
        <PRIMARY_INSTRUCTOR>Y</PRIMARY_INSTRUCTOR>
        <CLASS_DEPT_CODE>TST2</CLASS_DEPT_CODE>
        <CLASS_COURSE_NBR>2010</CLASS_COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <INDIV_NAME>2, instructor</INDIV_NAME>
        <PRIMARY_ACCESS_ID>inst2</PRIMARY_ACCESS_ID>
    </ROW>
    <ROW>
        <IDNUMBER>234555</IDNUMBER>
        <PRIMARY_INSTRUCTOR>Y</PRIMARY_INSTRUCTOR>
        <CLASS_DEPT_CODE>Biology</CLASS_DEPT_CODE>
        <CLASS_COURSE_NBR>101c</CLASS_COURSE_NBR>
        <SECTION_NBR>001</SECTION_NBR>
        <INDIV_NAME>2, instructor</INDIV_NAME>
        <PRIMARY_ACCESS_ID>inst2</PRIMARY_ACCESS_ID>
    </ROW>
</rows>
