=== lsuonline/lsuce-moodle/local/xml/schema/SPORTS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rows">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="ROW" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    
    <xs:complexType name="rowType">
        <xs:all>
            <xs:element name="IDNUMBER" type="xs:string"/>
            <xs:element name="SPORT_CODE_1" type="xs:string"/>
            <xs:element name="SPORT_CODE_2" type="xs:string"/>
            <xs:element name="SPORT_CODE_3" type="xs:string"/>
            <xs:element name="SPORT_CODE_4" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== lsuonline/lsuce-moodle/local/xml/sample_enrollment/SPORTS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../schema/SPORTS.xsd">
    <ROW>
        <IDNUMBER>1255</IDNUMBER>
	<SPORT_CODE_1>FBL</SPORT_CODE_1>
	<SPORT_CODE_2>GLF</SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
    <ROW>
        <IDNUMBER>1249</IDNUMBER>
	<SPORT_CODE_1>FBL</SPORT_CODE_1>
	<SPORT_CODE_2></SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
    <ROW>
        <IDNUMBER>1254</IDNUMBER>
	<SPORT_CODE_1></SPORT_CODE_1>
	<SPORT_CODE_2>GLF</SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
</rows>

=== lsuonline/lsuce-moodle/blocks/sgelection/enrollment/SPORTS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../schema/SPORTS.xsd">
    <ROW>
        <IDNUMBER>89its001</IDNUMBER>
	<SPORT_CODE_1>FBL</SPORT_CODE_1>
	<SPORT_CODE_2>GLF</SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
    <ROW>
        <IDNUMBER>89its003</IDNUMBER>
	<SPORT_CODE_1>FBL</SPORT_CODE_1>
	<SPORT_CODE_2></SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
    <ROW>
        <IDNUMBER>89its005</IDNUMBER>
	<SPORT_CODE_1></SPORT_CODE_1>
	<SPORT_CODE_2>GLF</SPORT_CODE_2>
	<SPORT_CODE_3></SPORT_CODE_3>
	<SPORT_CODE_4></SPORT_CODE_4>
    </ROW>
</rows>
