=== lsuonline/lsuce-moodle/local/xml/schema/STUDENT_DATA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rows">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="ROW" type="rowType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    
    <xs:complexType name="rowType">
        <xs:all>
            <xs:element name="IDNUMBER" type="xs:string"/>
            <xs:element name="REGISTRATION_DATE" type="xs:string"/>
            <xs:element name="YEAR_CLASS" type="xs:string"/>
            <xs:element name="CURRIC_CODE" type="xs:string"/>
            <xs:element name="KEYPAD_ID" type="xs:string"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== lsuonline/lsuce-moodle/blocks/sgelection/enrollment/STUDENT_DATA.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rows xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/STUDENT_DATA.xsd">
    <ROW>
        <IDNUMBER>89its001</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>GRAD</COLLEGE_CODE>
        <YEAR_CLASS>1</YEAR_CLASS>
        <CURRIC_CODE></CURRIC_CODE>
        <KEYPAD_ID>00156543</KEYPAD_ID>
    </ROW>
    <ROW>
        <IDNUMBER>89its002</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>UCAC</COLLEGE_CODE>
        <YEAR_CLASS>3</YEAR_CLASS>
        <CURRIC_CODE></CURRIC_CODE>
        <KEYPAD_ID></KEYPAD_ID>
    </ROW>
    <ROW>
        <IDNUMBER>89its003</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>HSS</COLLEGE_CODE>
        <YEAR_CLASS>5</YEAR_CLASS>
        <CURRIC_CODE></CURRIC_CODE>
        <KEYPAD_ID>00156543</KEYPAD_ID>
    </ROW>
    <ROW>
        <IDNUMBER>89its004</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>MCOM</COLLEGE_CODE>
        <YEAR_CLASS>6</YEAR_CLASS>
        <CURRIC_CODE></CURRIC_CODE>
        <KEYPAD_ID>00156543</KEYPAD_ID>
    </ROW>
    <ROW>
        <IDNUMBER>89its005</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>ENGR</COLLEGE_CODE>
        <YEAR_CLASS>7</YEAR_CLASS>
        <CURRIC_CODE>MSYSC</CURRIC_CODE>
        <KEYPAD_ID>00156543</KEYPAD_ID>
    </ROW>
    <ROW>
        <IDNUMBER>89its006</IDNUMBER>
        <REGISTRATION_DATE>2014-01-01</REGISTRATION_DATE>
        <COLLEGE_CODE>HSE</COLLEGE_CODE>
        <YEAR_CLASS>4</YEAR_CLASS>
        <CURRIC_CODE>MSYSC</CURRIC_CODE>
        <KEYPAD_ID>00156543</KEYPAD_ID>
    </ROW>
</rows>
